### ISSUE TITLE
缩略图和播放控制

### ISSUE THREAD

**Issue by wb1992321** [huyongli/TigerVideo#8]
请问一下那个缩略图如何自定义？因为我现在用的不是Glide而是Fresco
还有就是地下那个控制部分如何设置不显示或者自定义？

**Comment by huyongli** [comment]
1. VideoPlayerView有个方法可以获取缩略图的ImageView，方法VideoPlayerView.getThumbImageView()可以获取该ImageView，拿到之后你可以使用想用的方式去加载图片

2.你说的地下控制部分设置不显示是指一直不显示还是什么？如果要自定义底部控制条的样式的话可以继承VideoPlayerView重写布局，但是id不能变

@wb1992321 可以加QQ群106510493细聊
